### ISSUE TITLE
Can't use alias key

### ISSUE THREAD

**Issue by bilguun0203** [aikar/AdvancementCommand#2]
Plugin expecting to have command/commands for advancement with alias key.

#### Example config.yml
```yaml
on_advancement:
  - advancement: myplugin:broadcast_hello
    run_as: player
    command: broadcast hello
  - advancement: minecraft:husbandry/tame_an_animal
    alias: myplugin:broadcast_hello
```
#### Result
Error during startup
`[AdvancementCommand] Error in Command Configuration for advancement minecraft:husbandry/tame_an_animal at entry 2: Commands can not be empty`
